name: sitemap-docs

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 2 * * *"   # 每天 02:30 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate docs/sitemap.xml
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import os, subprocess, datetime, xml.sax.saxutils as sax
          BASE_URL  = "https://opmhoubue-eng.github.io/yuanmago-posts"  # 你站点的根（不要尾部斜杠）
          POSTS_DIR = "docs"                       # GitHub Pages 的项目页目录
          OUT_FILE  = os.path.join(POSTS_DIR, "sitemap.xml")

          os.makedirs(POSTS_DIR, exist_ok=True)

          def git_last_commit_iso(p:str):
            try:
              s = subprocess.check_output(
                ["git","log","-1","--pretty=format:%cI","--", p],
                text=True, stderr=subprocess.DEVNULL
              ).strip()
              return s or None
            except Exception:
              return None

          def file_mtime_iso(p:str):
            ts = datetime.datetime.utcfromtimestamp(os.path.getmtime(p))
            return ts.replace(microsecond=0).isoformat() + "Z"

          urls = []
          for root, _, files in os.walk(POSTS_DIR):
            for name in files:
              if not name.lower().endswith(".html"):
                continue
              full = os.path.join(root, name)
              rel  = os.path.relpath(full, POSTS_DIR).replace(os.sep, "/")
              loc  = f"{BASE_URL}/{rel}"
              last = git_last_commit_iso(full) or file_mtime_iso(full)
              urls.append((loc, last))

          urls.sort(key=lambda x: x[0])  # 稳定输出，避免无意义 diff

          with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
            f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
            for loc, last in urls:
              f.write("  <url>\n")
              f.write(f"    <loc>{sax.escape(loc)}</loc>\n")
              f.write(f"    <lastmod>{last}</lastmod>\n")
              f.write("  </url>\n")
            f.write("</urlset>\n")

          print(f"OK: wrote {OUT_FILE} with {len(urls)} urls.")
          PY

      - name: Commit & push if changed
        shell: bash
        run: |
          set -e
          FILE="docs/sitemap.xml"
          # 标记为 intent-to-add，保证第一次也能被检测到
          git add -N "$FILE" >/dev/null 2>&1 || true
          if git status --porcelain "$FILE" | grep -q .; then
            git config user.name  "actions-bot"
            git config user.email "actions@github.com"
            git add "$FILE"
            git commit -m "chore: update sitemap.xml [skip ci]"
            git pull --rebase origin main || true
            git push origin HEAD:main
            echo "pushed $FILE"
          else
            echo "no changes"
