name: Build & Commit Sitemap (docs)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 2 * * *"   # 每天 02:30 UTC（北京 10:30）
  workflow_dispatch: {}

permissions:
  contents: write   # 允许回写仓库

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要 git 历史获取 lastmod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate docs/sitemap.xml
        run: |
          python3 docs/generate_sitemap.py
          echo "==== Preview ===="
          head -n 20 docs/sitemap.xml || true
          echo "================="

      - name: Commit & push if changed
        run: |
          set -e
          if git status --porcelain | grep -q "docs/sitemap.xml"; then
            git config user.name  "actions-bot"
            git config user.email "actions@github.com"
            git add docs/sitemap.xml
            git commit -m "chore: update docs/sitemap.xml [skip ci]"
            git push
            echo "✅ sitemap.xml 已更新并推送。"
          else
            echo "ℹ️ 无变化，无需提交。"
          fi
