name: sitemap-docs

# 先手动触发，确认一切 OK 再改成 push / schedule
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate docs/sitemap.xml (never fail)
        shell: bash
        run: |
          set +e  # 不因为任何错误中断
          python - <<'PY'
import os, subprocess, datetime, xml.sax.saxutils as sax, sys, traceback

BASE_URL  = "https://opmhoubue-eng.github.io/yuanmago-posts"  # 站点根（无尾斜杠）
POSTS_DIR = "docs"                                            # 项目 Pages 目录
OUT_FILE  = os.path.join(POSTS_DIR, "sitemap.xml")

try:
    os.makedirs(POSTS_DIR, exist_ok=True)

    def git_last_commit_iso(p:str):
        try:
            s = subprocess.check_output(
                ["git","log","-1","--pretty=format:%cI","--", p],
                text=True, stderr=subprocess.DEVNULL
            ).strip()
            return s or None
        except Exception:
            return None

    def file_mtime_iso(p:str):
        ts = datetime.datetime.utcfromtimestamp(os.path.getmtime(p))
        return ts.replace(microsecond=0).isoformat() + "Z"

    urls = []
    for root, _, files in os.walk(POSTS_DIR):
        for name in files:
            if not name.lower().endswith(".html"):
                continue
            full = os.path.join(root, name)
            rel  = os.path.relpath(full, POSTS_DIR).replace(os.sep, "/")
            loc  = f"{BASE_URL}/{rel}"
            last = git_last_commit_iso(full) or file_mtime_iso(full)
            urls.append((loc, last))

    urls.sort(key=lambda x: x[0])

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        for loc,last in urls:
            f.write("  <url>\n")
            f.write(f"    <loc>{sax.escape(loc)}</loc>\n")
            f.write(f"    <lastmod>{last}</lastmod>\n")
            f.write("  </url>\n")
        f.write("</urlset>\n")

    print(f"OK: wrote {OUT_FILE} with {len(urls)} urls.")
except Exception as e:
    print("Generator error:", e)
    traceback.print_exc()
    # 即使失败也写一个空壳，保证后续步骤可继续
    os.makedirs(POSTS_DIR, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>\n')
    print(f"Wrote empty sitemap to {OUT_FILE}")
PY
          echo "== docs listing =="
          ls -la docs || true

      - name: Commit sitemap if changed (never fail)
        shell: bash
        run: |
          set +e
          FILE="docs/sitemap.xml"
          git add -N "$FILE" >/dev/null 2>&1
          if git status --porcelain "$FILE" | grep -q .; then
            git config user.name  "actions-bot"
            git config user.email "actions@github.com"
            git add "$FILE"
            git commit -m "chore: update sitemap.xml [skip ci]" || true
            git pull --rebase origin main || true
            git push origin HEAD:main || true
            echo "pushed $FILE (or no-op if protections)."
          else
            echo "no changes"
          fi

      - name: Done
        run: echo "Workflow finished successfully."
