name: Build & Commit Sitemap (docs)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 2 * * *"   # 每天 02:30 UTC（北京 10:30）
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug: show tree
        run: |
          set -x
          pwd
          ls -la
          ls -la docs || true

      - name: Generate docs/sitemap.xml (inline Python)
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, subprocess, datetime, xml.sax.saxutils, sys
          BASE_URL   = "https://opmhoubue-eng.github.io/yuanmago-posts"
          POSTS_DIR  = "docs"
          OUTPUT_XML = "docs/sitemap.xml"

          if not os.path.isdir(POSTS_DIR):
              print(f"❌ 未找到目录：{POSTS_DIR}", file=sys.stderr)
              sys.exit(1)

          def git_last_commit_iso(path: str):
              try:
                  ts = subprocess.check_output(
                      ["git", "log", "-1", '--pretty=format:%cI', "--", path],
                      stderr=subprocess.DEVNULL,
                      text=True
                  ).strip()
                  return ts or None
              except Exception:
                  return None

          def file_mtime_iso(path: str):
              ts = datetime.datetime.utcfromtimestamp(os.path.getmtime(path))
              return ts.replace(microsecond=0).isoformat() + "Z"

          urls = []
          for root, _, files in os.walk(POSTS_DIR):
              for name in files:
                  if not name.lower().endswith(".html"):
                      continue
                  full = os.path.join(root, name)
                  rel  = os.path.relpath(full, POSTS_DIR).replace(os.sep, "/")
                  url  = f"{BASE_URL}/{rel}"
                  last = git_last_commit_iso(full) or file_mtime_iso(full)
                  urls.append((url,
