name: sitemap-docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        run: python3 docs/generate_sitemap.py || true

      - name: Show docs dir
        run: ls -la docs || true

      - name: Commit sitemap if changed
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@github.com"
          git add -N docs/sitemap.xml || true
          if git status --porcelain docs/sitemap.xml | grep -q .; then
            git add docs/sitemap.xml
            git commit -m "update sitemap.xml [skip ci]" || true
            git push || true
            echo "pushed"
          else
            echo "no changes"
