name: sitemap

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 2 * * *"   # 每天 02:30 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        id: sm
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://opmhoubue-eng.github.io/yuanmago-posts/
          path-to-root: docs
          include-pdf: false

      - name: Commit sitemap if changed
        run: |
          set -e
          FILE="${{ steps.sm.outputs.sitemap-path }}"
          echo "sitemap path: $FILE"
          if ! git diff --quiet -- "$FILE"; then
            git config user.name  "actions-bot"
            git config user.email "actions@github.com"
            git add "$FILE"
            git commit -m "update sitemap.xml [skip ci]"
            git push
          else
            echo "no changes"
          fi
